"""
inspector.py

Creates an agent to analyze the JSON files generated by the profiler.
"""

import json
from discovery.utils.reader import get_datasource
from discovery.utils.writer import get_storage
from discovery.utils import assistant, manager, executor

from pathlib import Path


# Assigning the SKILL as the system prompt
def load_skill(skill_name) -> str:
    skill_path = Path(__file__).parent / f"{skill_name}.md"
    print(f" Skill {skill_name}.md loaded.")
    return skill_path.read_text(encoding="utf-8")


def read_data_sample(source_type: str, table_name: str, filter: dict = None, sample_size: int = 50, **kwargs) -> dict:
    source = get_datasource(
        source_type=source_type,
        **kwargs
    )
    cursor = source.read_table(table_name=table_name, filter=filter, sample_size=sample_size)
    rows = cursor.fetchall()

    # Convert cursor results to list of dicts   
    columns = [desc[0] for desc in cursor.description]
    return [dict(zip(columns, row)) for row in rows]


def inspect_structure_from_profile(
    domain_name:     str,
    storage_type:    str,
    **kwargs
):
    """
        Receives the profiling JSON from the previous steps and spins up agents to
         analyze its structure and write in the stroage.
    """
    reading_kwargs, writting_kwargs = manager.manage_input_output_paths(
        storage_type,
        io_type='profiler-inspector',
        input_path=kwargs.get('input_path'),
        output_path=kwargs.get('output_path'),
        input_bucket=kwargs.get('input_bucket'),
        output_bucket=kwargs.get('output_bucket'),
    )

    storage = get_storage(storage_type=storage_type, **reading_kwargs)
    profile_json = storage.read_json_from_storage(f"{reading_kwargs["folder_path"]}/{domain_name}")

    system_prompt = load_skill(skill_name="STRUCTURE")

    for datasource, profile in profile_json.items():
        inspector_messages = [
                 {
                     "role": "user",
                     "content": f"""
                         Analyze the data of {datasource}, with the provided JSON: 
                             {profile}
                         """
                 },
                 {
                     "role": "assistant",
                     "content": f"""I'll analyze the {datasource} table data and provide you with a comprehensive discovery report covering Primary Keys, Foreign Keys, Orchestration, and Relationships. Here is the report:"""
                 }
             ]
        
        print(f" Inspecting structure of Datasource: {datasource}.")
    
        response = assistant.chat(
            stream_text=False,
            messages=inspector_messages,
            model="claude-haiku-4-5",
            max_tokens=1000,
            system=system_prompt
            )
        results = response.content[0].text

        storage = get_storage(storage_type, **writting_kwargs)
        storage.write_json_to_storage(content={datasource: {"analysis": results}}, domain_folder=domain_name, analysis_type="structure")

        print(f" Structure of {datasource} inspected. File in storage. Length of analysis: {len(results)} caracteres.")

    return print(f"Structure inspection finished.")


def build_filters(profiles: dict) -> dict:
    filters = {}

    for datasource_name, datasource_info in profiles.items():
        print(f"Loading filter for datasource {datasource_name}")

        filters[datasource_name] = []

        for column_name, column_info in datasource_info["columns"].items():

            distinct_values = column_info.get("distinct", {}).get("values")

            if distinct_values:
                for value in distinct_values:
                    filters[datasource_name].append(
                        {
                            "column": column_name,
                            "value_to_filter": value
                        }
                    )
        print(f"Filters for datasource {datasource_name} loaded. Length: {len(filters[datasource_name])}")

    return filters

def inspect_pattern_from_profile(
        domain_name:     str,
        storage_type:    str,
        source_type:     str,
        **kwargs
    ):
    """
        Receives the filter dict from the previous steps and spins up agents to
         analyze its behavior, through dynamic filtering.
    """

    reading_kwargs, writting_kwargs = manager.manage_input_output_paths(
        storage_type,
        io_type='profiler-inspector',
        input_path=kwargs.get('input_path'),
        output_path=kwargs.get('output_path'),
        input_bucket=kwargs.get('input_bucket'),
        output_bucket=kwargs.get('output_bucket'),
    )

    storage = get_storage(storage_type=storage_type, **reading_kwargs)
    profile_json = storage.read_json_from_storage(f"{reading_kwargs["folder_path"]}/{domain_name}")
    filters = build_filters(profile_json)
    
    # To be able to query the data and observe patterns 
    system_prompt = load_skill(skill_name="PATTERNS")

    for datasource, filter_list in filters.items():
        print(f"\nProcessing: {datasource} ({len(filter_list)} filters)")

        samples = []
        for i, f in enumerate(filter_list):
            print(f"  Querying filter {i + 1}/{len(filter_list)}: {f['column']} = {f['value_to_filter']}")
            try:
                result = read_data_sample(
                    source_type=source_type,
                    table_name=datasource,
                    filter={datasource: f},
                )
                samples.append({"filter": f, "result": result})
            except Exception as e:
                samples.append({"filter": f, "error": str(e)})

        observer_messages = [
        {
            "role": "user",
               "content": (
                f"Analyze the behavior of datasource '{datasource}'.\n"
                f"Below are data samples for each filter combination.\n"
                f"Write a comprehensive behavior analysis.\n\n"
                f"Samples:\n{json.dumps(samples, indent=2, default=str)}"
            ),
        }
    ]
            
        response = assistant.chat(
            stream_text=False,
            messages=observer_messages,
            model="claude-sonnet-4-6",
            max_tokens=8000,
            system=system_prompt
        )
            
        analysis = response.content[0].text

        storage = get_storage(storage_type, **writting_kwargs)
        storage.write_json_to_storage(content={datasource: {"analysis": analysis}}, domain_folder=domain_name, analysis_type="pattern")

        print(f" Pattern of {datasource} inspected. File in storage. Length of analysis: {len(analysis)} caracteres.")

    return print(f"Pattern inspection finished.")
