"""
inspector.py

Creates an agent to analyze the JSON files generated by the profiler.
"""
from discovery.utils import executor
from discovery.utils.reader import get_datasource
from discovery.utils.writer import get_storage
from discovery.utils import assistant

from pathlib import Path


# Assigning the SKILL as the system prompt
def load_skill(skill_name) -> str:
    skill_path = Path(__file__).parent / f"{skill_name}.md"
    print(f" Skill {skill_name}.md loaded.")
    return skill_path.read_text(encoding="utf-8")


def read_profiles(storage_type: str, folder_path: str) -> dict:
    storage = get_storage(
        storage_type=storage_type,
        folder_path=folder_path
    )
    return storage.read_json_from_storage(folder_path)


def read_data_sample(source_type: str, table_name: str, filter: dict = None, sample_size: int = 50, **kwargs) -> dict:
    source = get_datasource(
        source_type=source_type,
        **kwargs
    )
    cursor = source.read_table(table_name=table_name, filter=filter, sample_size=sample_size)
    rows = cursor.fetchall()

    # Convert cursor results to list of dicts
    columns = [desc[0] for desc in cursor.description]
    return [dict(zip(columns, row)) for row in rows]

read_data_sample__schema = {
    "name": "read_data_sample",
    "description": """
        Reads a sample of records from a table in the specified data source.
        Use this tool when you need to inspect actual data values rather than
        metadata or profiling information. Supports optional filtering and
        configurable sample size.
    """,
    "input_schema": {
        "type": "object",
        "properties": {
            "source_type": {
                "type": "string",
                "description": """
                    Type of data source to query.
                    Supported values: 'snowflake', 'csv'.
                """
            },
            "table_name": {
                "type": "string",
                "description": """
                    Name of the table to sample data from.
                """
            },
            "filter": {
                "type": "object",
                "description": """
                    Optional filter to apply before sampling.
                    Example:
                    {"<name_of_datasource>": {"column": "<name_of_column>", "value_to_filer":"value_1"}}
                    """
            },
            "sample_size": {
                "type": "integer",
                "description": """
                    Maximum number of rows to return.
                    Defaults to 1000.
                """,
                "default": 1000
            }
        },
        "required": [
            "source_type",
            "table_name"
        ]
    }
}


def inspect_structure_from_profile(profile_json: dict):
    """
        Receives the profiling JSON from the previous steps and spins up agents to
         analyze its structure.
    """
    messages = []

    system_prompt = load_skill(skill_name="STRUCTURE")

    for datasource, profile in profile_json.items():
        inspector_messages = [
                 {
                     "role": "user",
                     "content": f"""
                         Analyze the data of {datasource}, with the provided JSON: 
                             {profile}
                         """
                 },
                 {
                     "role": "assistant",
                     "content": f"""I'll analyze the {datasource} table data and provide you with a comprehensive discovery report covering Primary Keys, Foreign Keys, Orchestration, and Relationships. Here is the report:"""
                 }
             ]
        
        print(f" Inspecting structure of Datasource: {datasource}.")
    
        response = assistant.chat(
            stream_text=False,
            messages=inspector_messages,
            model="claude-sonnet-4-6",
            max_tokens=1000,
            system=system_prompt
            )
        response = response.content[0].text
        messages.append(response)

        print(f" Structure of {datasource} inspected. Lenght of analysis: {len(response)} caracteres.")
    
    return messages
    
def build_filters(profiles: dict) -> dict:
    filters = {}

    for datasource_name, datasource_info in profiles.items():
        print(f"Loading filter for datasource {datasource_name}")

        filters[datasource_name] = []

        for column_name, column_info in datasource_info["columns"].items():

            distinct_values = column_info.get("distinct", {}).get("values")

            if distinct_values:
                for value in distinct_values:
                    filters[datasource_name].append(
                        {
                            "column": column_name,
                            "value_to_filter": value
                        }
                    )
        print(f"Filters for datasource {datasource_name} loaded. Lenght: {len(filters[datasource_name])}")

    return filters

def observe_behavior_from_profile(filters: dict):
    """
        Receives the filter dict from the previous steps and spins up agents to
         analyze its behavior, through dynamic filtering.
    """
    
    tools_functions = {
        "read_data_sample": read_data_sample
    }
    tools_schemas = [
        read_data_sample__schema
    ]
    messages = []

    # To be able to query the data and observe patterns 
    system_prompt = load_skill(skill_name="PATTERNS")

    for datasource, values in filters.items():
        print(f"Sending request for pattern analysis of datasource {datasource}.")
        
        observer_messages = [ {
                     "role": "user",
                     "content": f"""
                         Query the datasource {datasource} filtering the following values, one a a time:
                             {values}
                         """,
                     "role": "assistant",
                     "content": f"""I'll query the NATION datasource with each of the filters you provided. Here is the analysis for {datasource}:"""
                 }]
    
        assistant.chat(
            stream_text=True,
            messages=observer_messages,
            model="claude-haiku-4-5",
            max_tokens=1000,
            system=system_prompt,
            tools=tools_schemas,
            tools_functions=tools_functions
        )
        
        messages.append(observer_messages)
    
    return messages

if __name__ == "__main__":
    profile_json = read_profiles(storage_type='local',  folder_path='/Users/julianasampar/Desktop/learning_dev/personal_dev/pyprojects/others/archive/agent_test')
    #print(profile_json)
    #inspect_structure_from_profile(profile_json)
    filters = build_filters(profile_json)
    observe_behavior_from_profile(filters)
